// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: phxrpc/rpc/phxrpc.proto

#ifndef PROTOBUF_phxrpc_2frpc_2fphxrpc_2eproto__INCLUDED
#define PROTOBUF_phxrpc_2frpc_2fphxrpc_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/descriptor.pb.h>
// @@protoc_insertion_point(includes)

namespace phxrpc {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_phxrpc_2frpc_2fphxrpc_2eproto();
void protobuf_AssignDesc_phxrpc_2frpc_2fphxrpc_2eproto();
void protobuf_ShutdownFile_phxrpc_2frpc_2fphxrpc_2eproto();


// ===================================================================


// ===================================================================

static const int kCmdIDFieldNumber = 2000000;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MethodOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< ::google::protobuf::int32 >, 5, false >
  CmdID;
static const int kOptStringFieldNumber = 2000001;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MethodOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  OptString;
static const int kUsageFieldNumber = 2000002;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MethodOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  Usage;

// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace phxrpc

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_phxrpc_2frpc_2fphxrpc_2eproto__INCLUDED
