/* phxrpc_search_dispatcher.h

 Generated by phxrpc_pb2service from search.proto

 Please DO NOT edit unless you know exactly what you are doing.

*/

#include "phxrpc_search_dispatcher.h"

#include "search.pb.h"
#include "phxrpc_search_service.h"
#include "phxrpc/http.h"
#include "phxrpc/file.h"
#include <errno.h>

SearchDispatcher :: SearchDispatcher( SearchService & service, phxrpc::DispatcherArgs_t * dispatcher_args )
    : service_( service ), dispatcher_args_(dispatcher_args)
{
}

SearchDispatcher :: ~SearchDispatcher()
{
}

const phxrpc::HttpDispatcher< SearchDispatcher >::URIFuncMap & SearchDispatcher :: GetURIFuncMap()
{
    static phxrpc::HttpDispatcher< SearchDispatcher >::URIFuncMap uri_func_map = {
        {"/search/PHXEcho", &SearchDispatcher::PHXEcho},
        {"/search/Search", &SearchDispatcher::Search},
        {"/search/Notify", &SearchDispatcher::Notify}};
    return uri_func_map;
}

int SearchDispatcher :: PHXEcho( const phxrpc::HttpRequest & request, phxrpc::HttpResponse * response )
{
    dispatcher_args_->server_monitor->SvrCall(-1, "PHXEcho", 1);

    int ret = 0;

    google::protobuf::StringValue req;
    google::protobuf::StringValue resp;

    //unpack request
    {
        if( ! req.ParseFromString( request.GetContent() ) )
        {
            phxrpc::log( LOG_ERR, "ERROR: FromBuffer fail size %zu ip %s",
                request.GetContent().size(), request.GetClientIP() );
            return -1 * EINVAL;
        }
    }

    //logic process
    {
        if( 0 == ret ) ret = service_.PHXEcho( req, &resp );
    }

    //pack response
    {
        if( ! resp.SerializeToString( &( response->GetContent() ) ) )
        {
            phxrpc::log( LOG_ERR, "ERROR: ToBuffer fail ip %s", request.GetClientIP() );
            return -1 * ENOMEM;
        }
    }

    phxrpc::log( LOG_DEBUG, "RETN: PHXEcho = %d", ret );

    return ret;
}

int SearchDispatcher :: Search( const phxrpc::HttpRequest & request, phxrpc::HttpResponse * response )
{
    dispatcher_args_->server_monitor->SvrCall(1, "Search", 1);

    int ret = 0;

    search::SearchRequest req;
    search::SearchResult resp;

    //unpack request
    {
        if( ! req.ParseFromString( request.GetContent() ) )
        {
            phxrpc::log( LOG_ERR, "ERROR: FromBuffer fail size %zu ip %s",
                request.GetContent().size(), request.GetClientIP() );
            return -1 * EINVAL;
        }
    }

    //logic process
    {
        if( 0 == ret ) ret = service_.Search( req, &resp );
    }

    //pack response
    {
        if( ! resp.SerializeToString( &( response->GetContent() ) ) )
        {
            phxrpc::log( LOG_ERR, "ERROR: ToBuffer fail ip %s", request.GetClientIP() );
            return -1 * ENOMEM;
        }
    }

    phxrpc::log( LOG_DEBUG, "RETN: Search = %d", ret );

    return ret;
}

int SearchDispatcher :: Notify( const phxrpc::HttpRequest & request, phxrpc::HttpResponse * response )
{
    dispatcher_args_->server_monitor->SvrCall(2, "Notify", 1);

    int ret = 0;

    google::protobuf::StringValue req;
    google::protobuf::Empty resp;

    //unpack request
    {
        if( ! req.ParseFromString( request.GetContent() ) )
        {
            phxrpc::log( LOG_ERR, "ERROR: FromBuffer fail size %zu ip %s",
                request.GetContent().size(), request.GetClientIP() );
            return -1 * EINVAL;
        }
    }

    //logic process
    {
        if( 0 == ret ) ret = service_.Notify( req, &resp );
    }

    //pack response
    {
        if( ! resp.SerializeToString( &( response->GetContent() ) ) )
        {
            phxrpc::log( LOG_ERR, "ERROR: ToBuffer fail ip %s", request.GetClientIP() );
            return -1 * ENOMEM;
        }
    }

    phxrpc::log( LOG_DEBUG, "RETN: Notify = %d", ret );

    return ret;
}


